#!/usr/bin/env bash
# InsightBench full environment setup (evaluation + data collection + interact scenes).
#
# Includes CuRobo for motion planning (~20-30 min CUDA compile on first install).
# CuRobo is required for:
#   - scripts/collect_demo.py   (demonstration data collection)
#   - scene_interact/           (interactive CuRobo-driven scenes)
#
# For evaluation only (no CuRobo), use install_eval.sh instead.
#
# Usage:
#   bash install.sh [ENV_NAME]    # default: env_insightbench
#
# After install, activate with:
#   conda activate ENV_NAME

set -e

ENV_NAME="${1:-env_insightbench}"
ISAACLAB_ROOT="${ISAACLAB_ROOT:-/home/seonho/workspace/IsaacLab}"
INSIGHTBENCH_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CUROBO_ROOT="${CUROBO_ROOT:-/home/seonho/workspace/curobo}"
LEROBOT_ROOT="${ISAACLAB_ROOT}/lerobot"
MINICONDA_ROOT="${MINICONDA_ROOT:-${HOME}/miniconda3}"
CONDA_BIN="${MINICONDA_ROOT}/bin/conda"

require_dir() {
    local path="$1"
    local name="$2"
    local hint="$3"

    if [[ ! -d "${path}" ]]; then
        echo "ERROR: ${name} does not exist: ${path}" >&2
        echo "       ${hint}" >&2
        exit 1
    fi
}

require_file() {
    local path="$1"
    local name="$2"
    local hint="$3"

    if [[ ! -f "${path}" ]]; then
        echo "ERROR: ${name} does not exist: ${path}" >&2
        echo "       ${hint}" >&2
        exit 1
    fi
}

require_executable() {
    local path="$1"
    local name="$2"
    local hint="$3"

    if [[ ! -x "${path}" ]]; then
        echo "ERROR: ${name} is not executable or does not exist: ${path}" >&2
        echo "       ${hint}" >&2
        exit 1
    fi
}

require_dir "${ISAACLAB_ROOT}" "ISAACLAB_ROOT" "Set ISAACLAB_ROOT=/path/to/IsaacLab and rerun."
require_file "${ISAACLAB_ROOT}/_isaac_sim/setup_conda_env.sh" "Isaac Sim conda setup script" "Check that ISAACLAB_ROOT points to an IsaacLab checkout with Isaac Sim installed."
require_dir "${ISAACLAB_ROOT}/source/isaaclab" "Isaac Lab source package" "Check that ISAACLAB_ROOT points to a complete IsaacLab checkout."
require_dir "${ISAACLAB_ROOT}/source/isaaclab_assets" "Isaac Lab assets package" "Check that ISAACLAB_ROOT points to a complete IsaacLab checkout."
require_dir "${ISAACLAB_ROOT}/source/isaaclab_tasks" "Isaac Lab tasks package" "Check that ISAACLAB_ROOT points to a complete IsaacLab checkout."
require_dir "${LEROBOT_ROOT}" "LeRobot fork" "Expected at ISAACLAB_ROOT/lerobot; set ISAACLAB_ROOT to the checkout that contains it."
require_dir "${MINICONDA_ROOT}" "MINICONDA_ROOT" "Set MINICONDA_ROOT=/path/to/miniconda3 and rerun."
require_executable "${CONDA_BIN}" "conda executable" "Check MINICONDA_ROOT or set MINICONDA_ROOT=/path/to/miniconda3."
require_dir "${CUROBO_ROOT}" "CUROBO_ROOT" "Set CUROBO_ROOT=/path/to/curobo and rerun."

echo "============================================================"
echo " InsightBench  [FULL]  environment setup"
echo " Conda env    : ${ENV_NAME}"
echo " IsaacLab     : ${ISAACLAB_ROOT}"
echo " InsightBench : ${INSIGHTBENCH_ROOT}"
echo " Miniconda    : ${MINICONDA_ROOT}"
echo " CuRobo       : ${CUROBO_ROOT}"
echo "============================================================"

# ─── 1. Create conda env ──────────────────────────────────────────────────────
if "${CONDA_BIN}" env list | grep -q "^${ENV_NAME} "; then
    echo "[SKIP] Conda env '${ENV_NAME}' already exists."
else
    echo "[1/6] Creating conda env: ${ENV_NAME} (Python 3.11)"
    "${CONDA_BIN}" create -y -n "${ENV_NAME}" python=3.11
fi

CONDA_PIP="${MINICONDA_ROOT}/envs/${ENV_NAME}/bin/pip"

# ─── 2. Add Isaac Sim to the conda env (via activate hook) ───────────────────
ACTIVATE_DIR="${MINICONDA_ROOT}/envs/${ENV_NAME}/etc/conda/activate.d"
mkdir -p "${ACTIVATE_DIR}"

cat > "${ACTIVATE_DIR}/isaac_sim_paths.sh" << EOF
#!/usr/bin/env bash
# Auto-generated by InsightBench install.sh
source ${ISAACLAB_ROOT}/_isaac_sim/setup_conda_env.sh
# libstdc++ fix for Isaac Sim linker errors:
export LD_LIBRARY_PATH=\${CONDA_PREFIX}/lib:\${LD_LIBRARY_PATH}
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6
# IsaacLab root for asset paths (used by franka.py and scene configs)
export ISAACLAB_PATH=${ISAACLAB_ROOT}
EOF

echo "[2/6] Isaac Sim activate hook written."

# ─── 3. Install PyTorch (cu128 build — works with CUDA driver 12.4+) ──────────
echo "[3/6] Installing PyTorch 2.7.0+cu128"
${CONDA_PIP} install torch==2.7.0 torchvision torchaudio \
    --index-url https://download.pytorch.org/whl/cu128 --quiet

# ─── 4. Install Isaac Lab (editable) ──────────────────────────────────────────
# setuptools<70 needed: provides pkg_resources required by legacy deps (flatdict)
${CONDA_PIP} install "setuptools<70" --quiet
echo "[4/6] Installing Isaac Lab packages (editable)"
${CONDA_PIP} install -e "${ISAACLAB_ROOT}/source/isaaclab" --no-build-isolation --quiet
${CONDA_PIP} install -e "${ISAACLAB_ROOT}/source/isaaclab_assets" --no-build-isolation --quiet
${CONDA_PIP} install -e "${ISAACLAB_ROOT}/source/isaaclab_tasks" --no-build-isolation --quiet

# ─── 5. Install CuRobo (CUDA compilation — takes ~20-30 min) ─────────────────
echo "[5/6] Installing CuRobo (CUDA compilation, please wait...)"
echo "      Log: /tmp/curobo_build.log"
# Must point to CUDA 12.5+ to match PyTorch cu128.
# /usr/local/cuda symlink may point to an older version — override explicitly.
CUDA_HOME=/usr/local/cuda-12.5 PATH=/usr/local/cuda-12.5/bin:${PATH} \
    ${CONDA_PIP} install -e "${CUROBO_ROOT}" --no-build-isolation > /tmp/curobo_build.log 2>&1 \
    && echo "      CuRobo OK" \
    || { echo "      CuRobo build FAILED — check /tmp/curobo_build.log"; exit 1; }

# ─── 6. Install LeRobot fork + InsightBench + pinned deps ─────────────────────
echo "[6/6] Installing LeRobot fork and InsightBench"
${CONDA_PIP} install -e "${LEROBOT_ROOT}" --quiet
${CONDA_PIP} install -e "${INSIGHTBENCH_ROOT}" --quiet

# Pin versions to match env_isaaclab (resolves lerobot/isaaclab conflicts):
#   numpy<2 required by isaaclab; gymnasium==1.2.0 required by isaaclab;
#   opencv 4.11.x is last version compatible with numpy 1.x
${CONDA_PIP} install \
    "numpy==1.26.4" \
    "gymnasium==1.2.0" \
    "opencv-python==4.11.0.86" \
    omegaconf Pillow packaging h5py botocore --quiet
# Remove headless opencv pulled in by lerobot (conflicts with numpy 1.x)
${CONDA_PIP} uninstall opencv-python-headless -y 2>/dev/null || true

echo ""
echo "============================================================"
echo " DONE. Activate with:"
echo "   conda activate ${ENV_NAME}"
echo ""
echo " Verify:"
echo "   python -c \"from isaaclab.app import AppLauncher; print('OK')\""
echo "   python -c \"import curobo; print('CuRobo OK')\""
echo ""
echo " Collect demo data:"
echo "   python scripts/collect_demo.py --object door --asset_id <ID> \\"
echo "       --num_envs 8 --headless --enable_cameras"
echo "============================================================"
